core:
  command-aliases: 'goldenenchants,genchants,ge'
  lang: en
  prefix: 'GoldenEnchants'

general:
  tasks:
    arrow-trails:
      tick-time: 1
    passive-enchants:
      tick-time: 80
  enchantments:
    disabled:
    - some_enchant
    - enchant_name
    - enchant_name2
    max-item-golden-enchants: 3
    sword-enchants-applies-to-axes: true
    bow-enchants-applies-to-crossbows: true
    elytra-as-chestplate: true
    allow-passive-enchants-for-mobs: false
  enchantment-table:
    max-golden-enchants: 2
    golden-enchant-chance: 60.0

tiers:
  common:
    name: '&fCommon'
    color: '&f'
    chance: 75.0
  rare:
    name: '&aRare'
    color: '&a'
    chance: 45.0
  exotic:
    name: '&9Exotic'
    color: '&9'
    chance: 20.0
  legendary:
    name: '&6Legendary'
    color: '&6'
    chance: 5.0